server {
  listen 80;
  server_name _;
  client_max_body_size 1024m;

  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_request_buffering on;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
    proxy_pass http://api-gateway:8000/api/;
  }

  location /health {
    proxy_pass http://api-gateway:8000/health;
  }
}
